# Generated by Django 3.2.18 on 2023-02-14 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('price', models.IntegerField()),
                ('image1', models.ImageField(blank=True, upload_to='posts/', verbose_name='Картинка1')),
                ('image2', models.ImageField(blank=True, upload_to='posts/', verbose_name='Картинка2')),
                ('image3', models.ImageField(blank=True, upload_to='posts/', verbose_name='Картинка3')),
                ('image4', models.ImageField(blank=True, upload_to='posts/', verbose_name='Картинка4')),
                ('image5', models.ImageField(blank=True, upload_to='posts/', verbose_name='Картинка5')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
